### ISSUE TITLE
Probabilistic Search based on URI

### ISSUE THREAD

**Issue by ianibo** [bbcarchdev/quilt#1]
Just logging here so we don't forget

As a part of our BBC RES Connected Studio development event we came up against the following issue::

We are using a pluggable text mining module which returns a list concept identifiers. In our prototype, we have implemented a trivial [modular] search in bbc.co.uk/programmes using the Label predicate from identified concepts (IE Phrase matches on label text implies a dc:subject relation). However, when RES contains information about BBC programmes, what we would really like is probabilistic search which can be passed a list of concept identifiers and return documents ranked higher which have more subject concept hits. Boolean searching is not appropriate for our demonstrator as a search around the OCR specification for history, "Key Question 1" returns the following concepts:

"http://dbpedia.org/resource/Treaty_of_Versailles",
"http://dbpedia.org/resource/World_War_I",
"http://dbpedia.org/resource/France",
"http://dbpedia.org/resource/United_States",
"http://dbpedia.org/resource/Palace_of_Versailles",
"http://dbpedia.org/resource/Georges_Clemenceau",
"http://dbpedia.org/resource/Paris_Peace_Conference,_1919",
"http://dbpedia.org/resource/Germany"

In an ideal world, we could search RES for "EducationalResources" / "CreativeWorks" which have these concepts as a subject - with those resources containing more concepts ranking higher (Existing algorithms for term frequency seem applicable to this problem). _probably_ this could be implemented quite easily by indexing the named graph for a resource in a modern engine like ES, with concepts as non-parsed components.

Alternatively, we would like to be able to iterate over the full content of RES to populate an ES index which would give us this probabilistic interface. This might be appropriate if RES is not going to carry subject predicates as the app still needs to be able to find resources by subject.

HTH
e & the gooii team

**Comment by ajtucker** [comment]
One way to do something like this in SPARQL is to count the number of dct:subjects that match a given set of concepts, e.g. given the following example RDF:

```
@prefix db: <http://dbpedia.org/resource/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix : <http://example.com/> .

:res1 a :CreativeWork ;
  dct:subject db:Treaty_of_Versailles ;
  dct:subject db:World_War_I ;
  dct:subject db:United_States ;
.

:res2: a :CreativeWork ;
  dct:subject db:France ;
.

:res3: a :CreativeWork ;
  dct:subject db:Palace_of_Versailles ;
  dct:subject db:Georges_Clemenceau ;
.

:res4 a :CreativeWork ;
  dct:subject db:Paris_Peace_Conference%2C_1919 ;
  dct:subject db:Germany ;
.
```

the following SPARQL query will give you back those resources having at least one of the given concepts as dct:subject in order with the most matches first:

```
prefix db: <http://dbpedia.org/resource/>
prefix dct: <http://purl.org/dc/terms/>

select ?res (count(?subj) as ?count) where {
  ?res dct:subject ?subj
  filter (?subj in (db:Treaty_of_Versailles, db:World_War_I, db:France,
                    db:United_States, db:Palace_of_Versailles,
                    db:Georges_Clemenceau, db:Paris_Peace_Conference%2C_1919,
                    db:Germany))
} group by ?res order by desc(?count)
```

**Comment by ianibo** [comment]
Very cool - learnt a bit of sparql there - thanks!!

On 30 September 2014 15:12, Alex Tucker notifications@github.com wrote:

> One way to do something like this in SPARQL is to count the number of
> dct:subjects that match a given set of concepts, e.g. given the following
> example RDF:
> 
> @prefix db: http://dbpedia.org/resource/ .
> @prefix dct: http://purl.org/dc/terms/ .
> @prefix : http://example.com/ .
> 
> :res1 a :CreativeWork ;
>   dct:subject db:Treaty_of_Versailles ;
>   dct:subject db:World_War_I ;
>   dct:subject db:United_States ;
> .
> 
> :res2: a :CreativeWork ;
>   dct:subject db:France ;
> .
> 
> :res3: a :CreativeWork ;
>   dct:subject db:Palace_of_Versailles ;
>   dct:subject db:Georges_Clemenceau ;
> .
> 
> :res4 a :CreativeWork ;
>   dct:subject db:Paris_Peace_Conference%2C_1919 ;
>   dct:subject db:Germany ;
> .
> 
> the following SPARQL query will give you back those resources having at
> least one of the given concepts as dct:subject in order with the most
> matches first:
> 
> prefix db: http://dbpedia.org/resource/
> prefix dct: http://purl.org/dc/terms/
> 
> select ?res (count(?subj) as ?count) where {
>   ?res dct:subject ?subj
>   filter (?subj in (db:Treaty_of_Versailles, db:World_War_I, db:France,
>                     db:United_States, db:Palace_of_Versailles,
>                     db:Georges_Clemenceau, db:Paris_Peace_Conference%2C_1919,
>                     db:Germany))
> } group by ?res order by desc(?count)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bbcarchdev/quilt/issues/1#issuecomment-57319524.

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by ianibo** [comment]
Actually - Follow-up Q, which I meant to ask Mo : Is there a public sparql
endpoint for acropolis?

On 30 September 2014 15:14, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Very cool - learnt a bit of sparql there - thanks!!
> 
> On 30 September 2014 15:12, Alex Tucker notifications@github.com wrote:
> 
> > One way to do something like this in SPARQL is to count the number of
> > dct:subjects that match a given set of concepts, e.g. given the following
> > example RDF:
> > 
> > @prefix db: http://dbpedia.org/resource/ .
> > @prefix dct: http://purl.org/dc/terms/ .
> > @prefix : http://example.com/ .
> > 
> > :res1 a :CreativeWork ;
> >   dct:subject db:Treaty_of_Versailles ;
> >   dct:subject db:World_War_I ;
> >   dct:subject db:United_States ;
> > .
> > 
> > :res2: a :CreativeWork ;
> >   dct:subject db:France ;
> > .
> > 
> > :res3: a :CreativeWork ;
> >   dct:subject db:Palace_of_Versailles ;
> >   dct:subject db:Georges_Clemenceau ;
> > .
> > 
> > :res4 a :CreativeWork ;
> >   dct:subject db:Paris_Peace_Conference%2C_1919 ;
> >   dct:subject db:Germany ;
> > .
> > 
> > the following SPARQL query will give you back those resources having at
> > least one of the given concepts as dct:subject in order with the most
> > matches first:
> > 
> > prefix db: http://dbpedia.org/resource/
> > prefix dct: http://purl.org/dc/terms/
> > 
> > select ?res (count(?subj) as ?count) where {
> >   ?res dct:subject ?subj
> >   filter (?subj in (db:Treaty_of_Versailles, db:World_War_I, db:France,
> >                     db:United_States, db:Palace_of_Versailles,
> >                     db:Georges_Clemenceau, db:Paris_Peace_Conference%2C_1919,
> >                     db:Germany))
> > } group by ?res order by desc(?count)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bbcarchdev/quilt/issues/1#issuecomment-57319524.
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo
> GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo
GoodReads: https://www.goodreads.com/user/show/3106516-ian-ibbotson

**Comment by nevali** [comment]
There isn't — although we might have an _unsupported_ read-only mirror at some point; what we don't want is people actually relying on it, because we wouldn't be able to give any kind of SLA on it (no more than anybody in their right mind would for a public MySQL endpoint)

**Comment by nevali** [comment]
This is being tracked as part of bbcarchdev/spindle#9, so I'm going to close this one.
