### ISSUE TITLE
Links to different serialisation sometime point all to the index

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/quilt#11]
See, e.g., http://acropolis.org.uk/?class=http%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2FDocument

**Comment by nevali** [comment]
This is a spindle issue, not quilt itself. It's related to https://github.com/bbcarchdev/spindle/issues/23 and https://github.com/bbcarchdev/spindle/issues/18

(The data is correct, it's just not hugely helpful)
