### ISSUE TITLE
N-Quads MIME type is misregistered

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/quilt#12]
Quilt does not return n-quads unless the ".nq" resource is used.
See https://gist.github.com/cgueret/ee4e746211d41b8a68a1

**Comment by nevali** [comment]
Thanks — sounds like the MIME type isn't being properly registered inside Quilt.

By the looks of things, it's missing hyphen here:

https://github.com/bbcarchdev/quilt/blob/live/libquilt/librdf.c#L53

(Reads `application/nquads` when it should be `application/n-quads`)

**Comment by cgueret** [comment]
Looks like a very easy fix then :-)
