### ISSUE TITLE
Search on URI is broken

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/quilt#13]
See, e.g., http://acropolis.org.uk/?uri=http://dbpedia.org/resource/Amsterdam

**Comment by nevali** [comment]
At first blush, this appears to be an operational rather than code issue; there's what should be a fix in progress (the change is necessary for other reasons, and it's likely that the underlying issue is manifesting in this way).

**Comment by nevali** [comment]
As suspected — this was an ops issue; marking invalid (as it's not actually a quilt bug).
