### ISSUE TITLE
Separate the OLO index results in HTML view

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/quilt#40]
Having everything together can be confusing for users browsing the content of the page

**Comment by nevali** [comment]
The data browser shouldn't do this, but there ought to be a separate 'results' section in the template which lists them, in a standard SERPS format.

**Comment by cgueret** [comment]
SERPS = https://en.wikipedia.org/wiki/State_Earnings-Related_Pension_Scheme ? :-)

**Comment by nevali** [comment]
Search Engine Results Pages :)
