### ISSUE TITLE
Support array values for parameters

### ISSUE THREAD

**Issue by nevali** [bbcarchdev/quilt#47]
e.g., if the query-string includes `foo=bar&foo=baz`, it should be possible for an engine to obtain both values `bar` and `baz` for the key `foo`, while not breaking when parameters are inadvertently supplied more than once for keys which only require a single-value.

**Comment by cgueret** [comment]
Is this a duplicate of https://github.com/bbcarchdev/quilt/issues/41 ?

**Comment by nevali** [comment]
Ah, you're correct; I couldn't find it when skimming.
