### ISSUE TITLE
Document license is not ported to the right URI during content negotiation

### ISSUE THREAD

**Issue by cgueret** [bbcarchdev/quilt#51]
Currently the data for Shakespeare does not pass the validator (see http://vm-10-100-0-3.ch.bbcarchdev.net/validate?uri=http%3A%2F%2Fshakespeare.acropolis.org.uk%2Fprogrammes%2FNGWA319F%23id) because we apply the license to `<http://shakespeare.acropolis.org.uk/programmes/NGWA319F> dct:licence <http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/>` whereas Quilt indicates that the document served is `http://shakespeare.acropolis.org.uk/programmes/NGWA319F.ttl`

If we change the data in the dump to apply the license to `http://shakespeare.acropolis.org.uk/programmes/NGWA319F.ttl` the data passes the validator but that URI does not get changed to, say, `http://shakespeare.acropolis.org.uk/programmes/NGWA319F.rdf` if RDF+XML is asked instead. So changing the accept of the validator will make the validation break.

More generally any one requesting the data should be able to verify its license. One option is to ensure that all our datasets have a license attached to all the possible serialisations (.rdf, .ttl, etc). Another would be to implement something to make sure Quilt is able to apply the license to the document it is returning. The latter could also be achieved by adding the license in the HTTP header (there is some relevant doc there https://bbcarchdev.github.io/inside-acropolis/#rights-link)

**Comment by nevali** [comment]
Dup of #35
